apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: default
data:
  RABBITMQ_HOST: cv-rabbitmq-amqp.rabbitmq.svc.cluster.local
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: guest
  RABBITMQ_PASS: guest