# https://docs.konghq.com/kubernetes-ingress-controller/1.2.x/guides/using-kongingress-resource/
apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: cv-kongingress-service-1
upstream:
  algorithm: least-connections
  # TODO SFS, use head approach to keep connection routing to the same node
  # hash_on: header
  # hash_fallback: ip
  # hash_on_header: hook-service
  healthchecks:
    active:
      http_path: /cv1/healthcheck
      type: http
      healthy:
        interval: 5
        successes: 3
      unhealthy:
        http_failures: 1
        interval: 5
    passive:
      healthy:
        successes: 3
      unhealthy:
        http_failures: 3
# TODO SFS, check on this later
# proxy:
#   protocol: http
#   path: /
#   connect_timeout: 10000
#   retries: 10
#   read_timeout: 10000
#   write_timeout: 10000
# routes:
#   route:
#     methods:
#     # - POST
#     - GET
#     paths:
#       /cv1/healthcheck
#     # regex_priority: 0
#     strip_path: true
#     preserve_host: true
#     protocols:
#     - http
#     - https